- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.12.2
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      args: [
        "--rcfile=.pylintrc",
        "--load-plugins=pylint.extensions.docparams",
        "-rn",  # Only display messages
        "-sn",  # Don't display the score
      ]
      language: system
      types: [python]
